# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Ruizhe Zhang
description:      
url:              www.cs.utexas.edu
baseurl:          /~rzzhang/

author:
  name:           'Ruizhe Zhang'

paginate:         5

gems: [jekyll-paginate]
